export const RouterName = {
  HOME: "/",
  PRODUCTS: "/products",
  PRODUCT_DETAIL: "/products/:id",
  CART: "/cart",
  ABOUT: "/about",
  LOGIN: "/login",
  HELP: "/help",
  CONTACT: "/contact",
  ADMIN: "/admin",
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_USERS: "/admin/users",
  ADMIN_PRODUCTS_DETAIL: "/admin/products/:id",
  ADMIN_USERS_DETAIL: "/admin/users/:id",
  ADMIN_INBOX: "/admin/inbox",
  REGISTER: "/register",
  ERROR: "/*",
};
